### ISSUE TITLE
Improve error handling to prevent panics

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope-rs#9] opened 2022-02-04 17:27 UTC
@eh-am has reported a panic when trying the example without launching pyroscope:

```
❯ RUST_BACKTRACE=1 cargo run                                                                                                    
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/basic`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyroscope-0.3.0/src/pyroscope.rs:343:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/library/core/src/panicking.rs:135:14
   2: core::panicking::panic
             at /rustc/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/library/core/src/option.rs:752:21
   4: pyroscope::pyroscope::PyroscopeAgent::_stop
             at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyroscope-0.3.0/src/pyroscope.rs:343:9
   5: pyroscope::pyroscope::PyroscopeAgent::stop
             at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyroscope-0.3.0/src/pyroscope.rs:367:15
   6: pyroscope::pyroscope::PyroscopeAgent::add_tags
             at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyroscope-0.3.0/src/pyroscope.rs:391:9
   7: basic::main
             at ./src/main.rs:25:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It seems this `unwrap` is the cause: https://github.com/pyroscope-io/pyroscope-rs/blob/main/src/pyroscope.rs#L343

Looking at the code, there seems to be quite a few `unwrap` calls, which may potentially crash the agent and the profiled application with it. It'd be nice to improve the error handling to make sure that whatever problem the agent encounters, it'll not panic (the profiled application shouldn't be affected by profiling problems).

**Comment by abeaumont** [comment] 2022-02-04 17:30
This is related to https://github.com/pyroscope-io/pyroscope/issues/786

**Comment by omarabid** [comment] 2022-02-06 17:51
Fixed in https://github.com/pyroscope-io/pyroscope-rs/commit/1254bcc9a3b0d76b7adbeb82ba21f33b875c0b39

(This fixes the cause of the problem, though it doesn't address the unwraps)

**Closed** 2022-02-14 22:31 UTC
Labels: enhancement
